# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mythical_mane", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientNote",
            fields=[
                (
                    "patient_note_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("universe_name", models.CharField(blank=True, max_length=200)),
                ("author_name", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=120)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "patient_note",
            },
        ),
    ]
